/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatataRouteImport } from './routes/patata'
import { Route as IndexRouteImport } from './routes/index'

const PatataRoute = PatataRouteImport.update({
  id: '/patata',
  path: '/patata',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patata': typeof PatataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patata': typeof PatataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patata': typeof PatataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patata'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patata'
  id: '__root__' | '/' | '/patata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatataRoute: typeof PatataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patata': {
      id: '/patata'
      path: '/patata'
      fullPath: '/patata'
      preLoaderRoute: typeof PatataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatataRoute: PatataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
